---
title: "Examples"
author: "LittleBeannie"
date: "9/11/2022"
output: html_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(gt)
library(BuyAHouse)
```


## Example 1
```{r}
house_value <- 36 * 1e4
monthly_cost(house_value = house_value, 
             property_tax = 2.5/100, 
             annual_other_tax = 6000, 
             monthly_hoa_fee = 200, 
             monthly_home_insurance = 150, 
             monthly_utility_fee = 300, 
             closing_fee = house_value * 0.07,
             year = 10, 
             saving_rate = 0.03, 
             down_payment = 0.2,
             mortgage_rate = 5.75/100,
             morrgage_year = 30)
```


## Example 2
```{r}
rent <- seq(2300, 4000, by = 100)

foo <- function(house_value, rent){
  ans <- monthly_cost(house_value = house_value, 
                      property_tax = 2.5/100, 
                      annual_other_tax = 6000, 
                      monthly_hoa_fee = 250, 
                      monthly_home_insurance = 150, 
                      monthly_utility_fee = 300, 
                      closing_fee = house_value * 0.07,
                      year = 10, 
                      saving_rate = 0.03, 
                      down_payment = 0.2,
                      mortgage_rate = 5.75/100,
                      morrgage_year = 30)
  return(ans - rent)
}

ans <- lapply(rent, 
              function(x){return(uniroot(foo, rent = x, interval = c(1e5, 1e6))$root)})

ans <- do.call(rbind, ans) %>% 
  as.data.frame() %>% 
  mutate(rent = rent) %>% 
  rename(`house value` = V1) %>% 
  select(`house value`, rent) 

ans %>% 
  gt() %>% 
  tab_header(title = "The equivlance between renting and owning")
```


  

```{r}
rate1 <- 5/100/12
rate2 <- 8/100/12
house_value <- ans$`house value`

out <- lapply(house_value, 
              function(x){
                a1 <- repayment(x * 0.8, beta = rate1, m = 30*12)
                a2 <- repayment(x * 0.8, beta = rate2, m = 30*12)
                return(c(a1*30*12, a2*30*12, (a2 - a1)*30*12))})


do.call(rbind, out) %>% 
  as.data.frame() %>% 
  mutate(`house value` = house_value) %>% 
  rename(`lower rate` = V1, 
         `high rate` = V2, 
         diff = V3) %>% 
  select(`house value`, `lower rate`, `high rate`, diff) %>% 
  gt() %>% 
  tab_header(title = "The difference between lower/high rate")
```

